spring:
  application:
    name: taskflow-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/taskflow}
    username: ${DB_USERNAME:taskflow}
    password: ${DB_PASSWORD:taskflow}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs

taskflow:
  security:
    jwt:
      secret: ${JWT_SECRET:c3VwZXItc2VjcmV0LWRldi1vbmx5LWNoYW5nZS1pbi1wcm9kdWN0aW9uLXRhc2tmbG93LWFwaS1rZXk=}
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:1440}
      issuer: taskflow-api

logging:
  level:
    com.ryan.api: INFO
    org.hibernate.SQL: WARN
